### ISSUE TITLE
Page titles and URLs are truncated or wrap unexpectedly

### ISSUE THREAD

**Issue by pdehaan** [bwinton/SnoozeTabs#28]
### Steps to reproduce:

1. Go to http://www.cnn.com/2016/11/30/politics/donald-trump-cabinet-washington-movers/index.html
1. Snooze tab until a later date.
1. Click the "Snooze Tab" button in the toolbar.
1. Click "Managed Snoozed Tabs" button at the bottom of the dorohanger.

### Actual results
The snoozed tab results look poorly because the URL is ridiculous long.

### Expected results:
The snoozed tab titles and URLs should be truncated.
Note that the "Mozilla Firefox Start Page" title is truncated as well, plus the "Donald Trump keeps DC swampy" title is truncated to "Donald Trump keeps DC".

**Note:** We should possibly pretty the displayed URLs to the domain (minus "www." prefix, if present). Or, display the full URL (minus protocol+www, and just truncate the URL to a single line).

---

![donald_trump_keeps_dc_swampy_-_cnnpolitics_com](https://cloud.githubusercontent.com/assets/557895/20777843/8a0ca66e-b71e-11e6-83cd-8fc18a5409fd.png)

**Comment by pdehaan** [comment]
Not a fan of my regex, but hey...

```js
function makeEntry(item) {
  let entry = document.createElement('li');
  entry.classList.add('entry');
  entry.innerHTML = `<img src="${item.icon || '../icons/nightly.svg'}" class="icon"></div>
    <div class="content">
      <div class="title">${item.title || '&nbsp;'}</div>
      <div class="url">${item.url.replace(/(https?:\/\/)(www\.)?/g, '') || '&nbsp;'}</div>
    </div>
    <div class="date">${item.date || 'Later'}<div>`;
  return entry;
}
```

Truncation handled via boring-ol CSS:

```css
.entry .title {
  font-size: 14px;
  line-height: 18px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.entry .url {
  color: #999;  
  font-size: 12px;
  line-height: 13px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```

Totally looks like:

![mozilla_firefox_start_page](https://cloud.githubusercontent.com/assets/557895/20778037/f28d4ad0-b71f-11e6-9f96-35c7a99822c8.png)
